# Generated by Django 5.2.1 on 2025-06-05 13:43

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_planned_date',
            field=models.DateField(default=api.models.get_default_planned_date),
        ),
    ]
