# Generated by Django 5.2 on 2025-05-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categorie', models.IntegerField()),
                ('nom_categorie', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_commande', models.IntegerField()),
                ('id_utilisateur', models.IntegerField()),
                ('date_commande', models.DateField()),
                ('statut_commande', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='commandeproduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_commande_produit', models.IntegerField()),
                ('id_commande', models.IntegerField()),
                ('id_produit', models.IntegerField()),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paiement', models.IntegerField()),
                ('id_commande', models.IntegerField()),
                ('montant', models.IntegerField()),
                ('date_paiement', models.DateField()),
                ('mode_paiement', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_produit', models.IntegerField()),
                ('nom', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('prix', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('image_url', models.CharField(max_length=256)),
                ('id_categorie', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_utilisateur', models.IntegerField()),
                ('nom', models.CharField(max_length=256)),
                ('prenom', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=256)),
                ('mot_de_passe', models.CharField(max_length=256)),
                ('adresse', models.CharField(max_length=256)),
                ('telephone', models.CharField(max_length=256)),
            ],
        ),
    ]
